import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ChakraProvider } from "@chakra-ui/react";
import { GoogleOAuthProvider } from "@react-oauth/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};



export default function RootLayout({

  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <ChakraProvider>
        <GoogleOAuthProvider clientId="429891697483-fbsjt9h0rem8gmruqmvegfk61ognvpfh.apps.googleusercontent.com">
        {children}
        </GoogleOAuthProvider>
       
      </ChakraProvider>
        </body>
    
    </html>
  );
}
